live() delegate() and on()


table that has lot of rows...how do you know if the user clicks tr,,,,and mouseenter or leave...or click to every tr...

300 different event handlers...

3 diff options to handle efficieantly...

they are live() delegate() and on() - provide a way to attach evets at higher level...

bubbles up and then parents will handle... 

when a child is clicked , it can actually bubble up...

allow childern to be added to a container without explicitly attaching an event handler to each child...



---Using live() old api , removed ...

$('.someClass').live('click', someFunction);  --- event wont happen at the child level...it will bubble up to the document object...The document object handles events by default....


anythign that has someClass on it, click event wont be attached to that class...it will bubble up to the document object.....anychild that has someClass is clicked is bubble up...


Stop live event handling using die)_ 

$('.someClass').die()  -- wil detach from the documnet object..


